import os

def generate_monthly_report(output_filename="Monthly_Report.pdf"):
    try:
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
        from reportlab.lib.styles import getSampleStyleSheet
    except ImportError as exc:
        raise RuntimeError(f"reportlab is required to generate PDFs: {exc}")

    current_dir = os.path.dirname(os.path.abspath(__file__))
    root_dir = os.path.dirname(current_dir)
    pdf_path = os.path.join(root_dir, output_filename)

    doc = SimpleDocTemplate(pdf_path)
    styles = getSampleStyleSheet()
    
    content = [
        Paragraph("Monthly Executive Report", styles["Title"]),
        Spacer(1, 12),
        Paragraph("This is the monthly performance report generated by the Self-Learning AI Decision Support Ecosystem.", styles["BodyText"])
    ]
    
    doc.build(content)
    print(f"Monthly Report Generated: {pdf_path}")
    return pdf_path
